version: "3.1"
services:
        db:
                image: mysql
                container_name: db
                command: --default-authentication-plugin=mysql_native_password
                environment:
                        MYSQL_ROOT_PASSWORD: test
                        MYSQL_DATABASE: myDb
                        MYSQL_USER: user
                        MYSQL_PASSWORD: test
                ports:
                        - "33306:3306"
                volumes:
                        - ./dump:/docker-entrypoint-initdb.d
                        - ./conf:/etc/mysql/conf.d
                        - persistent:/var/lib/mysql
        backend:
                build:
                        context: ./backend
                        dockerfile: Dockerfile
                container_name: pythonBackend
                ports:
                        - 15000:5000
                depends_on:
                        - db
        frontend:
                build:
                        context: ./frontend
                        dockerfile: Dockerfile
                container_name: vue_app_container
                ports:
                        - '8080:8080'
                volumes:
                        - ./frontend:/app
                environment:
                        - NODE_ENV=development
                depends_on:
                        - backend

volumes:
        persistent: